apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  SERVICE_NAME: {{ .Values.env.SERVICE_NAME | quote }}
  ENV: {{ .Values.env.ENV | quote }}
  MARKET: {{ .Values.env.MARKET | quote }}
  VERSION: {{ .Values.env.VERSION | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  PUBLIC_BASE_URL: {{ .Values.env.PUBLIC_BASE_URL | quote }}
  JWT_ISSUER: {{ .Values.env.JWT_ISSUER | quote }}
  JWT_AUDIENCE: {{ .Values.env.JWT_AUDIENCE | quote }}
  DB_DSN: {{ .Values.env.DB_DSN | quote }}
