name: proteon-services

networks:
  proteon:
    external: true

services:
  identity-service:
    image: proteon/identity-service:dev
    container_name: proteon-identity-service
    env_file:
      - ../../services/identity/.env.docker
    environment:
      RUNTIME_MODE: docker
    ports:
      - "9091:8081"
    networks:
      - proteon
    restart: unless-stopped
